import Image from "next/image";
import Link from "next/link";
import PageHero from "./ui/PageHero";
import { PageSection, SectionIntro, PageNav } from "./ui/Interior";
import { ArrowRight } from "./ui/Button";
import SponsorTiers from "./SponsorTiers";
import { sponsors } from "@/data/sponsorsData";
import { FUNDING_USES } from "@/data/sponsorship";
import { SITE, SPONSORSHIP_PACKAGE } from "@/data/site";

export default function Sponsors() {
  return <div className="home-page inner-page">
    <PageHero eyebrow="Partnerships / Build with McMaster Exo" title="Back the people." accent="Power the progress." image="/ace_2026/sponsors.jpg" imageAlt="Sponsor logos on the frame of the McMaster exoskeleton worn by a pilot outdoors." focal="50% 43%" imageCaption="Your support becomes something real." actions={<><a href="#partner-contact" className="home-button">Become a partner <ArrowRight /></a><a href={SPONSORSHIP_PACKAGE} target="_blank" rel="noopener noreferrer" className="home-text-link">Sponsorship package <span className="pdf-label">PDF ↗</span></a></>} below={<PageNav items={[{href:"#impact",label:"Your impact"},{href:"#tiers",label:"Sponsorship levels"},{href:"#our-sponsors",label:"Our partners"},{href:"#partner-contact",label:"Get in touch"}]} />}>
      Help students turn ambitious ideas into working hardware. Your support funds the components, manufacturing and competition experiences that make the build possible.
    </PageHero>
    <PageSection id="impact" tone="light"><SectionIntro eyebrow="01 / From support to a working suit" title="See what your support makes possible.">Every actuator and circuit board has a job to do. Funding and in-kind support help us source the right parts and put student engineering to work.</SectionIntro><div className="funding-grid">{FUNDING_USES.map((use,i)=><article key={use.label}><span className="eyebrow">0{i+1}</span><h3>{use.label}</h3><p>{use.detail}</p></article>)}</div><div className="sponsor-impact-note"><p>50+ students. Multiple disciplines. A shared engineering challenge.</p><Link href="/design" className="home-text-link">Explore the work you’re backing <ArrowRight /></Link></div></PageSection>
    <PageSection id="tiers"><SectionIntro eyebrow="02 / Ways to partner" title="Choose your part in the build.">From a first contribution to a logo on the suit, each level supports the team and gives your company a place in our story.</SectionIntro><SponsorTiers /><div className="in-kind-note"><span className="eyebrow">More than funding</span><p>Components, machining time and software licences are welcome, too. Talk with us about what your company can contribute.</p></div></PageSection>
    <PageSection id="our-sponsors" tone="light"><SectionIntro eyebrow="03 / The people in our corner" title="Built with their support.">Thank you to the organisations helping us design, build and compete.</SectionIntro><div className="partner-roster">{(["gold","silver","bronze"] as const).map(tier=><div key={tier}><h3 className="partner-tier-heading">{tier}<span>{sponsors[tier].length} partners</span></h3><ul className="partner-logo-grid">{sponsors[tier].map(sponsor=><li key={sponsor.name}><a href={sponsor.website} target="_blank" rel="noopener noreferrer"><Image src={sponsor.logo} alt={sponsor.name} width={200} height={Math.round(200/(sponsor.aspect??2.5))} unoptimized={sponsor.logo.endsWith(".svg")} className={sponsor.invert?"invert":""} /></a></li>)}</ul></div>)}</div><div className="affiliate-row"><p className="eyebrow">Our student society</p><a href="https://www.macengsociety.ca/" target="_blank" rel="noopener noreferrer"><Image src="/MES_logo.png" alt="" width={90} height={45} /><span>McMaster Engineering Society<strong>Our governing student society</strong></span><ArrowRight /></a></div></PageSection>
    <PageSection id="partner-contact" tone="surface"><div className="partner-contact"><div><p className="eyebrow">04 / Let’s make something happen</p><h2 className="home-heading">The next step is<br />a conversation.</h2><p>Tell us about your company and how you’d like to support the team. We can talk through sponsorship, in-kind contributions and the work ahead.</p><a href={`mailto:${SITE.email}?subject=Sponsorship%20enquiry`} className="home-button">Email us about partnering <ArrowRight /></a></div><aside><span className="eyebrow">Take a closer look</span><h3>The sponsorship<br />proposal.</h3><p>Our team, our plans, and the full sponsorship benefits in one document.</p><a href={SPONSORSHIP_PACKAGE} target="_blank" rel="noopener noreferrer" className="home-text-link">Open the package <span className="pdf-label">PDF ↗</span></a></aside></div></PageSection>
  </div>;
}
